# Generated by Django 3.2.5 on 2021-08-12 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20210804_1410'),
        ('App', '0002_auto_20210806_0038'),
    ]

    operations = [
    ]
